# Expose your documentation as JSON swagger compliant
nelmio_api_doc_json:
    path: /api/doc.json
    controller: nelmio_api_doc.controller.swagger
    methods: [GET]

nelmio_api_doc_ui:
    path: /api/doc
    controller: nelmio_api_doc.controller.swagger_ui
    methods: [GET]

## Requires the Asset component and the Twig bundle
## $ composer require twig asset
#app.swagger_ui:
#    path: /api/doc
#    methods: GET
#    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
